package CREATIONAL_DESIGN_PATTERNS.FACTORY.Database;

import CREATIONAL_DESIGN_PATTERNS.FACTORY.Abstract_Factory.ABSTRACT_FACTORY;

public interface DATABASE {
    public ABSTRACT_FACTORY createFactory();
}
